name: Software Testing Lab
services:
  mongo:
    image: mongo
    container_name: testing_mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data/seeding
    environment:
      MONGO_INITDB_ROOT_USERNAME: testing_user
      MONGO_INITDB_ROOT_PASSWORD: testing_password
      MONGO_INITDB_DATABASE: test

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://testing_user:testing_password@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

volumes:
  db_data:
    driver: local
